var isidGuide = [
    {
        title: "The task",
        content: "<p>During the summer of 2018, I was given the opportunity to be a part of <b>IBM Design's Patterns internship</b>. I, along with 19 other designers from all over the country and all kinds of backgrounds, spent 10 weeks at the Design Studio in Austin, Texas.</p> <p>The interns were split into small groups and assigned a project for the summer. Our team, Team Code Blue, was made up of a visual designer, a UX designer, a UX researcher, and another front-end developer. While the other teams were assigned internal IBM projects, we were paired with the International Society of Infectious Diseases (ISID). ISID had reached out to IBM in hopes of developing a solution to <b>empower healthcare workers practicing infection prevention and control (IPC) in low- and middle-income countries (LMIC)</b>. ISID has a <a href=\"http://www.isid.org/education/guide-to-infection-control-in-the-healthcare-setting/\" target=\"_blank\">Guide to Infection Control in the Healthcare Setting</a>, in both print and PDF form, but it isn't accessible and has problems reaching people in LMICs. ISID needed a prototype to present at the 2018 International Meeting on Emerging Diseases and Surveillance in order to get funding to develop the solution we designed.</p>"

    },
    {
        title: "Oh boy that's a huge problem space",
        content: "<p>We were thrown into a domain that none of us had any experience with. We spent days researching, scrambling to understand the world of IPC, the types of healthcare workers, and their unique pain points. Initially, we narrowed in on the community healthcare workers (CHW) of sub-Saharan Africa. These CHWs are personnel trusted by their communities, responsible for very \"on the field\" work and yet armed with less than ideal education and resources.</p> <p>We were blinded by our idealism, so drawn to the idea that we could design a solution to reach millions of people, especially the people in LMICs who needed help the most. The fact that these CHWs mostly carried feature phones and lived in areas with little to no Internet were not obstacles in our eyes but exciting challenges to overcome.</p> <p>Slowly we realized that this was not feasible. We had less than two months to interview CHWs in vastly different time zones and with unreliable cell signals; the developers had never done mobile development before, much less development for feature phones or for users with spotty Internet.</p>"
    },
    {
        title: "Our solution",
        content: "<p>And so we, a little sadly, let go of all the research (and the oddly emotional connection we had made with our CHW persona) and settled on something more realistic. <b>Our final idea was to design a mobile application that organized the ISID Guide into a more readable and searchable format, as well as supported localized content-creation by infection control specialists on a hopsital level.</b></p><p>Hospital Acquired Infections are disproportionally common in some LMIC hospitals but can be significantly lowered with proper IPC practices. The current sources of such practices are guides (like ISID's) and infection control specialists. Unfortunately, guides tend to be dense, tough to parse through, difficult to use to make actionable decisions, and more geared towards higher resource settings. And while infection control specialists can help with all these issues, the ratio of doctors and nurses to infection control specialists in a hospital isn't great; infection control specialists often have to run around and repeatedly answer similar questions, thus taking away their time from more complex cases. Ideally, our solution would <b>accessibly present general IPC guidelines, and also allow infection control personnel to quickly share their IPC knowledge through short, actionable content.</b></p>"
    },
    {
        title: "Preparing for Development (or, I reluctantly enter the world of React)",
        content: "<p>I had come in as a front-end developer, but the intensely collaborative structure of the internship let me explore the other disciplines and work closely alongside the designers on our team. After enjoying a few weeks of design thinking, brainstorming, and researching, however, it was time I returned to the world of development.</p> <p>We settled on using React Native for our platform agnostic solution. I had never worked with React Native (or even React!) before, so I spent about a week bodyslamming myself into videos and textbooks and online tutorials. I was <b>hesitant to start producing code because I didn't think I was good enough</b>, but we were rapidly running out of time. Once I began coding though, I started understanding React Native better and faster. It was actually pretty fun, building the screens and playing around which them on the emulator. I spent the last few weeks consuming our designer's Sketch mockups and spitting out code as fast as possible.</p>"
    },
    {
        title: "Development (or, I actually find myself enjoying mobile development, maybe a little too much)",
        content: "<p>Our team didn't follow a single linear path while designing. Rather than waiting for the researcher to bring feedback to the designer, and then waiting for the designer to finish prototyping screens before coding, everything kind of happened at once. Our researcher was sending out surveys to ISID guide readers and remotely interviewing potential users about concepts and mockups. Our designers were working on an InVision prototype while also trying to take into consideration the user feedback from the researcher. And the developers were trying to turn the ever changing InVision prototype into code.</p><p>We had a <b>three step roadmap</b> for ISID. The short term goal was to develop a mobile app that was essentially a digital version of the ISID guide, along with a basic search on the guide's chapters and articles. The mid-term goal was to allow content creation, like announcements and protocols by infection control specialists to address local hospital needs. The long term vision was co-creation of content with regional governments and NGOs and connection of hospitals in similar settings to allow for protocol sharing. We planned to hand off <b>two separate deliverables</b> to ISID: a basic coded demo to represent the short term goal, and an InVision prototype to demonstrate mid-term goal features that wouldn't be feasible to code in time.</p><p>I, however, had other plans. The coded deliverable was originally planned to just be a couple chapters from the ISID guide and a search bar to match keywords to chapter titles. But I was so greedy, so <b>determined to code up as many of the InVision prototype features as I could</b>. In the end, I was able to implement some mid-term goal functionality like rudimentary commenting, protocol creation for the infection control specialists, pinning and favoriting. But my code was messy (I had a makeshift \"database\" to hold all the guide contents as well as any comments associated for each page, resulting in a disgusting arrays of arrays of objects of arrays and so on), I was probably stressing the other developer out, and I was pretty burnt out.</p>"
    },
    {
        title: "And the summer ends.",
        content: "<p>Last week was a whirwind of presentation practice and panicked last-minute coding. But the final presentation went wonderfully, our speakers were fantastic, and I was finally ready to let go of the code. In the end the functionality we got for the coded deliverable included: <b>search functionality that matches keywords to article titles and metatags, search suggestions, commenting, custom content creation/editing, and article pinning/favoriting</b>.</p><p>And after 10 hot weeks, I left Austin with some new friends, React Native experience developed at breakneck speeds, and a deeper appreciation for small, baby soft tacos.</p>"
    }
];