var socialMusic = [
    {
        title: "The problem",
        content: "<p>For our User Interface Design class, my team of four was given the general task to solve any problem related to <b>transportation</b>. We decided to focus on how mobile devices could improve the entertainment and safety aspects of walking alone. I think Pokemon GO was about 6 months old at the time (so not too stale), and we wanted to contribute to this exciting market. <b>How else could technology enhance walking and, more interestingly so, the other way around?</b></p> <p>Our final solution was a mobile app to make listening to music while walking a more social activity. It would allow direct interaction with other users and the environment, creating a unique playlist for each walk made up of songs received from passersby and landmarks. We developed this idea through a comprehensive design process involving user research, brainstorming, prototyping, and testing, all outlined below. I specifically contributed to our team of four by creating profiles for personas, low-fidelity sketches and storyboards of our top ideas, and the final InVision prototype.</p>"

    },
    {
        title: "The users",
        content: "<p>The first step was to collect data on our potential users. In order to determine our stakeholder groups, we conducted observations around campus and gave out surveys with demographic questions (e.g. about age, gender, general phone use). After analyzing the survey data, we narrowed down the following <b>stakeholders</b>: male nighttime walker, male daytime walker, female nighttime walker, female daytime walker. Our survey results indicated differences in behaviors and emotions between the genders and depending on what time of day one walked.</p> <p>I was in charge of creating <b>personas</b> for our stakeholders. Drawing from personalities, beliefs, and behaviors of myself, my peers, and the people we gathered data from, I produced 3 profiles of characters that would probably want to use whatever beautiful app we were to create.</p> <img src=\"./media/music_persona1.png\" alt=\"Persona 1\"> <img src=\"./media/music_persona2.png\" alt=\"Persona 2\"> <img src=\"./media/music_persona3.png\" alt=\"Persona 3\"> <p>Using the bios I wrote, another team member mapped out the experience each persona would have during a walk, noting their thoughts, feelings, and sense of safety as time progressed.</p>"

    },
    {
        title: "Brainstorming",
        content: "<p>During our brainstorming session, we came up with a list of 100 ideas that were all over the place but still relevant to our overarching theme of technology and walking. To make the list a little less overwhelming, we clustered our ideas into 6 categories (music, physical companion, digital companion, hands-free, road safety, and danger prevention). By merging aspects of similiar ideas we liked the most, we ended up with three distinct solutions. I was in charge of creating <b>low-fidelity sketches and storyboards</b> for each idea.</p> <p>1) Walking with Friends: a mobile application that provides the user with options (listen to calming music, call a friend, ask for nearby walking buddies, notify police) depending on their current inputted mood. This was most applicable for our male and female nighttime walker stakeholder groups.</p> <img src=\"./media/music_sketch1.png\" alt=\"Sketch for Walking with Friends\"> <img src=\"./media/music_storyboard1.png\" alt=\"Storyboard for Walking with Friends\"> <p>2) Hands-Free Entertainment: a mobile application that dictates the user's social media feed by verbalizing text posts and analyzing photos to generate audio/music it believes is representative of each image. This will reduce the amount of time and attention the user would normally need to read and scroll through a feed. This was intended for use by all stakeholders but would be best for male and female daytime walkers since the app would still require some level of engagement.</p> <img src=\"./media/music_sketch2.png\" alt=\"Sketch for Hands-Free Entertainment\"> <img src=\"./media/music_storyboard2.png\" alt=\"Storyboard for Hands-Free Entertainment\"> <p>3) Social Music: a mobile application that makes listening to music on a walk a more social activity. Each user has a queue of songs that are automatically added from playlists of locations and from personal playlists of other users of the applications they walk past. This was intended for use by all stakeholders but would be bes for male and female daytime walkers because the app doesn't really contribute to increasing the user's safety.</p> <img src=\"./media/music_sketch3.png\" alt=\"Sketch for Social Music\"> <img src=\"./media/music_storyboard3.png\" alt=\"Storyboard for Social Music\"> <p>We determined three <b>design criteria</b>: <b>entertainment value</b>, <b>safety</b> (measured by the sense of security the users themselves feel), and <b>required attention</b> (measured by interaction and ability for idle use). We used how well each idea contributed to each design criteria along with responses from other students in class to decide which app to proceed with. Ultimately, we received the most positive feedback and interest about our <b>Social Music</b> app, so the next step was to prototype.</p>"

    },
    {
        title: "Prototyping",
        content: "<img src=\"./media/music_prototype1.png\" alt=\"Home Screen Prototype\"> <img src=\"./media/music_prototype2.png\" alt=\"Main Screen Prototype\"> <p>When we finalized our solution, we realized that gender and time of day the user was walking wouldn't matter as much as the purpose and frequency of using our app, so we <b>edited our stakeholder groups:</b> <b>entertainment walker</b> (listens to music as a way to entertain during walks), <b>social walker</b> (seeks company while walking), <b>exerciser</b> (listens to music while running or jogging outside).</p> <p>For the entertainment walker, our solution stresses the entertainment feature of adding unique songs to their queue when passing landmarks, increasing interactions with reality. For the social walker, our solution provides a way to communicate with other people by sending random songs from personally curated playlists. For the exerciser, our solution addresses pedestrian safety by allowing minimal interaction, possibly gestures and voice control for pausing, skipping, and volume control.</p> <p>With this in mind, I created our interactive <b>prototype</b> with Photoshop and InVision. InVision is a great application, especially for turning flat images into a cohesive and connected project; I could, however, definitely tell there were some limitations in how responsive and realistic I could make our prototype. The prototype thus ended up being designed more for use with user testing of a specific section of our app (discussed in more detail later) and less representative of our entire app's functionalities. I'm also not very good at coming up with clever names for projects. In any case, you can <b>check it out</b> <a href=\"https://invis.io/CKF7SPODS#/228341047_Home\" target=\"_blank\">here</a>!</p> <p><b>Here is what we envisioned for the final app:</b> Each user sets up a profile and creates a personal playlist of their favorite songs. The app also has a database of landmarks (much like Pokemon GO gyms); users can submit songs to each location. When the user begins walking, they press the button to tell the app to start a playlist. As they walk, the app grabs random songs from playlists of locations and users they pass. If at any state, there are no songs ready in the queue, the app will play a random song from the user's favorites playlist. This will ideally create a musically unique and social walking experience for the user every time they walk. At the end of a walk, the user has the options to view their playlist, edit it by removing songs they didn't like too much, save it, and share it on various social media platforms.</p"
    },
    {
        title: "Testing",
        content: "<p>We gathered a handful of participants to follow a couple instructions to navigate our InVision prototype and asked some questions to <b>measure our design criteria</b>. To evaluate entertainment value, we asked for user emotions before, during, and after uses of our app. To evaluate safety, we asked subjective and straightforward questions about the user's trust in our solution. To evaluate required attention, we relied on survey questions (similar to those for the previous two criteria) as well as experimenter observations of the user.</p> <p>For our <b>benchmark testing</b>, we focused on the user interaction nearing the end of their walk, when the user would end their playlist, edit it, and share it on social media. Initially, we had chosen this because it required the most interaction and wanted to see if it required as little attention as we wanted. Ideally, we would have focused on the main part of the app, where the user receives songs and fiddles with controls (play, pause, skip, volume adjustment) while walking around, but our prototype was unfortunately too limited for any of these actions. Thus, we asked our participants to begin their walk's playlist, end their walk, and then view, edit, save, and share their final playlist.</p> <p>Overall, <b>feedback was positive!</b> There was no confusion on how to complete the benchmark tasks, and participant feedback confirmed that the app was <b>easy and intuitive to use</b>. Participants did express frustration at the lack of functionality. Most of the changes we seriously considered, therefore, were to <b>add features that participants deemed useful</b> instead of editing current ones. Were we to iterate and update our prototype, these are the <b>changes we would've made</b>:<br>1) Add ability to choose multiple social media platforms at once, instead of one at a time<br>2) Add ability to create a caption before selecting which platform to share to (resolves the violation of User Control and Freedom heuristic from <a href=\"https://www.nngroup.com/articles/ten-usability-heuristics/\" target=\"_blank\">Jakob Nielsen's Usability Heuristics</a>)<br>3) Allow playlist editing during walks by adding a save/delete button on each song when it plays<br>4) Make a more noticeable song deletion button<br>5) Don't automatically save a playlist if the user shares it (resolves the violation of Match between System and Real World heuristic)</p>"
    },
    {
        title: "Reflection",
        content: "<p>I appreciated having the chance to thoroughly go step-by-step in the design process and had the most fun making the persona profiles. Coming up with the list of 100 ideas during the brainstorming session was surprisingly difficult, but our team had each other to encourage and to bounce ideas off of, and we eventually ended up with a pretty neat solution.</p>"
    }
];